### ISSUE TITLE
Allow int sorting

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/oceandb-elasticsearch-driver#40]
https://github.com/oceanprotocol/oceandb-elasticsearch-driver/blob/develop/oceandb_elasticsearch_driver/plugin.py#L161

Any sort key is going to be mapped as text, and sorted as such.

Ex:   sort: [{ 'price.ocean': 'desc' }]

**Comment by ssallam** [comment]
Fixed in #41
Sorting in the live deployment is fixed as well.
